import Head from 'next/head'
import Image from 'next/image'
import LeftMenu from '../components/LeftMenu'


export default function Home() {
  return (
    <div>
      <Head>
        <title>let's talk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img.icons8.com/color/100/000000/chat--v1.png" />
      </Head>

      <LeftMenu />

      </div>
  )
}
